version: "3.9"
services:
    web:
        build: .
        restart: on-failure:3
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            # FLASK_DEBUG: 1
            # FLASK_APP: project/app.py
            # FLASK_ENV: development
            # FLASK_RUN_PORT: 8000
            # FLASK_RUN_HOST: 0.0.0.0
            DATABASE_URL: postgresql://postgres:password@db:5432/mydb

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
